version: '3.8'

services:
  app:
    image: 03_mongo_api:latest
    container_name: replica-apis
    ports:
      - "3000:3000"
    depends_on:
      - mongo-primary
      - redis01
    networks:
      - red01
    command: npm start
  mongo-primary:
    image: mongo
    command: mongod --replSet replica01
    ports:
      - "27017:27017"
    networks:
      - red01

  mongo-secondary1:
    image: mongo
    command: mongod --replSet replica01
    ports:
      - "27018:27017"
    networks:
      - red01

  mongo-secondary2:
    image: mongo
    command: mongod --replSet replica01
    ports:
      - "27019:27017"
    networks:
      - red01

  mongo-secondary3:
    image: mongo
    command: mongod --replSet replica01
    ports:
      - "27020:27017"
    networks:
      - red01

  redis01:
    image: redis/redis-stack:latest
    container_name: redis01
    ports:
      - "6379:6379"
      - "8001:8001"
    networks:
      - red01
    depends_on:
      - mongo-primary
      - mongo-secondary1
      - mongo-secondary2
      - mongo-secondary3

networks:
  red01:
    driver: bridge
